### ISSUE TITLE
Tone curve module soon to be deprecated

### ISSUE THREAD

**Issue by Mathys-Rituper** [jade-nl/dt.styles#2]
Hi ! As you may know, dt is moving on to a new scene related workflow which will soon render the tone curve module to be deprecated, which will make it ineffective and not usable anymore, ruining the presets. Are you planning on converting the presets to the replacement module (tone equalizer?)
thank you in advance !

**Comment by jade-nl** [comment]
> As you may know, dt is moving on to a new scene related workflow

It already has. As of 3.6, the current and latest stable version, the pixel work-flow defaults to *scene-referred*.

> which will soon render the tone curve module to be deprecated

There are no plans of deprecating the _tone curve_ module any time soon (if ever). I just asked on IRC to make sure of that and none of the devs have seen any indications that this is about to happen.

> which will make it ineffective and not usable anymore, ruining the presets.

No it will not.

It, the current tone curve module, is outside of the export-to-filmic part of the pipeline and thus outside of the scene-referred modules/workflow.

On a side note: Using display-referred modules doesn't invalidate the whole scene-referred workflow. The same restrictions to the display-referred modules apply as before: Watch out what you are doing when using them because pushing them too far can create artefact, halos and other nastiness. But they are still very(!) useful at times.

BTW: There are plans to make a _tone curve rgb_ module which will be part of the scene-referred workflow. Location in the pipeline and what it will be able to do is still a bit of a mystery though, there isn't even a preliminary PR/FR on GitHub about it, just devs talking about it at the moment. So it will be in version 3.10 at the earliest if I might hazard a guess.

Anyway: I'm not planning on converting the current presets/styles that use the *tone curve* module.

**Comment by johnny-bit** [comment]
Actually there's `rgb curve` module already present and no plans to deprecate `tone curve`

**Comment by jade-nl** [comment]
@johnny-bit 

True, but I've been under the impression that the `RGB Curve`  (and `RGB Levels`) aren't optimal. Both are linear and thus have "earned" a spot in the exposure-to-filmic part of the pipeline but they are both display referred in nature.

All this is a bit off-topic, then again, the original question has been answered :-)
